### ISSUE TITLE
The focus doesn't loop on mobile screen-reader.

### ISSUE THREAD

**Issue by manuelodelain** [vue-a11y/vue-focus-loop#3]
The focus doesn't loop on mobile screen-reader.
The focus changes by swipe gesture then the tab key logic doesn't apply.
Tested on iOS with VoiceOver.

A possible workaround would be to add `aria-visibility="hidden"` to all the page elements except the focus loop container.

sources:
- https://medium.com/@im_rahul/focus-trapping-looping-b3ee658e5177
- https://allyjs.io/tutorials/accessible-dialog.html

**Comment by manuelodelain** [comment]
theKashey/vue-focus-lock#16

**Comment by ktquez** [comment]
@manuelodelain 
I'll look at the links you sent me and add the corrections.

Thanks man

**Comment by ktquez** [comment]
@manuelodelain 

I added some features in versions [0.2.0](https://github.com/vue-a11y/vue-focus-loop/tree/v0.2.0) (Vue 2) and [1.1.0](https://github.com/vue-a11y/vue-focus-loop/tree/v1.1.0) (Vue 3).

I tested it on Talkback (Android) and it's working.

I can't currently test on VoiceOver, could you help me with that?

Thanks again.

**Comment by manuelodelain** [comment]
Sure @ktquez ! Sounds good :) I'll try to do that soon

**Comment by ktquez** [comment]
I will close this issue, but if the error persists, please, reopen.
Thanks
