### ISSUE TITLE
Autoinstall will throw an error in Vue 3.

### ISSUE THREAD

**Issue by LinusBorg** [vue-a11y/vue-focus-loop#4]
Vue 3 no longer provides a `use()` function on the global Vue object - plugins are installed on app instances.

So this line will throw an error:

https://github.com/vue-a11y/vue-focus-loop/blob/006081317c9c4605b4d41a36111f4dd5c8242236/src/plugin.ts#L13

**Comment by ktquez** [comment]
🤦‍♂️ I didn't even remember that.
Thanks @LinusBorg 

Fixed [v1.0.3](https://github.com/vue-a11y/vue-focus-loop/tree/v1.0.3)
