### ISSUE TITLE
Is it expected to return focus once the loop is deactivated?

### ISSUE THREAD

**Issue by dougalg** [vue-a11y/vue-focus-loop#5]
Right now, it seems that deactivating the focus loop will not return focus to the previously focused element. This seems like it would be a useful feature. I might be willing to look at making a PR for this feature if you think so?

**Comment by ktquez** [comment]
Hi @dougalg 

I would be grateful for your PR.

**Comment by ktquez** [comment]
@dougalg 

I added some features in versions [0.2.0](https://github.com/vue-a11y/vue-focus-loop/tree/v0.2.0) (Vue 2) and [1.1.0](https://github.com/vue-a11y/vue-focus-loop/tree/v1.1.0) (Vue 3).

You could test and see if everything is ok.

Thanks for using.

**Comment by dougalg** [comment]
@ktquez thank you so much, I will take a look! I'm so sorry I didn't have time to contribute to this in the end

**Comment by ktquez** [comment]
No problem, I'm grateful that you opened this issue.
